### PR TITLE
Use leading zeroes intrinsic

### LINKED ISSUE #111: vint64: failure to roundtrip 1048576
This number is encoded as `[0x8, 0x0, 0x0, 0x1]`, but decoding that again fails with a `LeadingZeroes` error.

Decoding `[0x8, 0xbb, 0x3, 0x1]` fails with the same error, which might be the same issue (this one I found while trying to make rustc use vint64 for metadata encoding).

### PR DESCRIPTION
**Pull request by jamesmunns**
Closes #111 

This uses the leading zeroes intrinsic, which gives a slight perf boost, as well as fixing the round trip issue, likely there is some wrong constant in the previous match impl.

```
     Running /tmp/.cargo-build-cache/release/deps/vint64-85b2e93ba12d6336
vint64/encode           time:   [5.5530 cycles 5.6138 cycles 5.6858 cycles]
                        change: [-7.5630% -6.5807% -5.8157%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 10 outliers among 100 measurements (10.00%)
  1 (1.00%) low mild
  7 (7.00%) high mild
  2 (2.00%) high severe
vint64/decode           time:   [16.3879 cycles 16.4438 cycles 16.5156 cycles]
                        change: [-0.1230% +1.7969% +3.7206%] (p = 0.08 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  3 (3.00%) high mild
  5 (5.00%) high severe
```

### CODE REVIEW

**Comment by jamesmunns** [comment]
As a note, the second commit, which uses unsafe, adds additional performance benefits. This is the measured delta against the first commit:

```
     Running /tmp/.cargo-build-cache/release/deps/vint64-85b2e93ba12d6336
vint64/encode           time:   [5.1884 cycles 5.2120 cycles 5.2388 cycles]
                        change: [-7.5053% -6.5646% -5.3148%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  5 (5.00%) high mild
  2 (2.00%) high severe
vint64/decode           time:   [16.2801 cycles 16.4015 cycles 16.5784 cycles]
                        change: [-6.4868% -4.4379% -2.4577%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 14 outliers among 100 measurements (14.00%)
  3 (3.00%) high mild
  11 (11.00%) high severe
```

File: rust/vint64/src/lib.rs [hunk 1]
```diff
@@ -73,7 +73,7 @@
 
 #![no_std]
 #![doc(html_root_url = "https://docs.rs/vint64/1.0.0")]
-#![forbid(unsafe_code)]
+// #![forbid(unsafe_code)]
```
Comment (tony-iqlusion) [inline rust/vint64/src/lib.rs]: Let's go with the `unsafe` solution as this function is definitely a hotspot in Veriform, which uses it to calculate the length of all of the length prefix tags in its TLV encoding.

Can you delete this line?

**Comment by tony-iqlusion** [comment]
Looks good!

I may have fixed the CodeCov token too, so if you delete that line (and ideally also rebase) the tests should hopefully pass as well.

**Comment by jamesmunns** [comment]
@tony-iqlusion I have added a safety note, and restored `unsafe_code` to a warning level (instead of `forbid`).

Should be ready to squash + merge.

**Review by tony-iqlusion — APPROVED** [review]
Looks like CodeCov is still broken, but otherwise this looks good
